#!/usr/bin/env python3
"""tests for prtm.py"""

import os
from subprocess import getstatusoutput

prg = './prtm.py'


# --------------------------------------------------
def test_exists():
    """exists"""

    assert os.path.isfile(prg)


# --------------------------------------------------
def test_usage():
    """usage"""

    rv, out = getstatusoutput(prg)
    assert rv != 0
    assert out.lower().startswith('usage:')


# --------------------------------------------------
def test_ok1():
    """runs ok"""

    rv, out = getstatusoutput(f'{prg} SKADYEK')
    assert rv == 0
    assert out == '821.392'


# --------------------------------------------------
def test_ok2():
    """runs ok"""

    prot = ''.join([
        'VLSTFVYNRWVKIVFDWNAHSLHYGPYTSYEVQDWAVAFYYFHYPFRLLL',
        'YFIHCKMHRICMAKVWMYLSKNCNQRHQAPIFYKATNNDWVAVIWPLYWN',
        'EQYNFNLMLDPASFWNSPDCYCFWNMCLAQTHKCLQMQKLPKRGWHITFR',
        'LEPMNGQRGARCRFAHYELRPDPWFEQFCRWHKSRCQVRSKMQIVWGNAF',
        'PRNRYSAPIPPCNMTQRNRDMPCGQWYIEITNPSPPMFMGQHAECYVGGT',
        'RWEHTGDYKMIVQVQDLQQAFQVWLQCVCRDNQHMDCMHTPFRNLMDDCR',
        'IYGSFFLKIGVKAEWYDMKQYWSQRESTMCGCVMCFDWAQFRVWILMDKW',
        'VVWSQTCERFKRCPLQVDCSDYFIGQQYWMQVTCYQISDTSTPCFNHDKW',
        'NMCQASQTHPYTMDLAGFFRSSEFLCQCMYIFWLQMLLFARCARPIPANV',
        'PVFPCMNIIDSSKQKMGRRNCQQNLWLGDTAHWRQDMTLPTEKQDNLECM',
        'WEQRHTWCFTDTPRRCPWRYWDIGCSPEHIKHLTEENCEELGYKHTPDDG',
        'NQFLCMHYDNQHDANWGMIGWQCWMKKFDLGASVKNCMNFFKLFWFNTCH',
        'KVDGAAEAYVWPNACYQWQFNSCEMEESFHCHHDNLIGARWLLIRDRLNA',
        'LNVQPYWYWHVIQQVYLESGKVAHPFSTYNWWIISMWYDLESRMVPFNIK',
        'EDAQGDWNTTLICEHTADCCTPMEVWTSFCCSCGVQKYAAVLWIKFYIWN',
        'GQVSNLKFVWATTHNGLSDDHYMSTIIMFICVRMRKHLIYCPLGFMEIVA',
        'FGGGRHYRHNWPHMTKNALNIQFGHFFHCEKMFVDVLQTMYYIWDQYFCA',
        'MGSCGMPMLQTMTNFDMILPDMAVEEHFMADGQAMYMLGTIVCWVSNCCV',
        'QWANPDYKNGYIDNNERMKPEMRGQAHFQEICIDNVAYCSPSSGIKHCFP',
        'QMNHYFRQYVRMRKEVANWIGETPCTQPSFQ'
    ])
    print(f'{prg} {prot}')
    rv, out = getstatusoutput(f'{prg} {prot}')
    assert rv == 0
    assert out == '117688.338'


# --------------------------------------------------
def test_ok3():
    """runs ok"""

    prot = ''.join([
        'LFDLGRDMNWGMMCWTIADFMPKGWRQWTGLDMYAAGMLHVEHLPIFHDD',
        'KQWFACECEDGRAQPKGHCKKVFKGSHVWYHPNYYWHNAKHCCAENISQS',
        'HISFVSGAIWNCKCERQYHDMSYHGPWKTWSTESMQKLNGAWLLYGNLDI',
        'YSCLLYAAEKFGMNMWPHTNLEDRDDSAVNTKNHPNYCDKFWGAKMRGAI',
        'EKQSMTCGGLNHFRDNGCTIRFPENAEEVFNMMPRMPQKCQAEVGFNQVL',
        'HGNVNSYDKPDDFFVTAKTIRKVWPSPVFEEKTYNYRADKRSNHLYGPCW',
        'MTGVQTPGLHCGCYYIWNCKQWFTFSHMRTMFDIDPMDCSNEKAMHFFYW',
        'FQLEVHRFNINPTACVAGLNFHYENEKNDPCFATHDKEWRMFFQEMIMMT',
        'MIVFRRAMAWSCDRSMKRREYCGLDWFHDEKFEIHSLQTDVQTDLSNPAY',
        'CCVAACSLAIVHVRPWNPHCAIQTLNQSQVLHCQPRCCTTEDNERNRGKF',
        'VWDQVFIKVAFQPNSLLNPNQGCVLLHWLVANKSWERLLQFCGWPTNKNN',
        'IKWGKGSLLASTRNHNKLEPPSQICECYYPAWFILPTCCLMEMCCHYWTK',
        'TSAHLPFHFHIGHKRQGQLPYFRSPQMCCAAGAGCQWMLSGTDFFWPEII',
        'YHWIIWMQRLEDRDTLERVCHSVNTKKKMYSYLINLVLDYQYSKKQQVRE',
        'SRDIEALEDQSFFKQVCVEYTDTSWREWSLPFRGHHVWVGGVRGFCCTPP',
        'QMKINKISNSHAPNNVNLWWYPRQWYLAKIWHSPKRTFARQQICLKNVHY',
        'DYKTSVIDDEGKQWDVGKGKIEPFQLSVWSPVRNCSNLWQLMGNRTCQWL',
        'PVPTTNFLWFAVTWWNCARYWVCIIGFTAHMAQTWEWPNDHCRFPEWRTK',
        'CRDHYRFSLGGNTDTQKCTHVGQNFNNNCVKTKEENQRSNWYKCPAEEAH',
        'ELLVMKGEFWSFVADMLYHPNGQRQAEFHHYMFEGYEPKYSIMAECTHC'
    ])
    print(f'{prg} {prot}')
    rv, out = getstatusoutput(f'{prg} {prot}')
    assert rv == 0
    assert out == '118526.626'
